"""ONE set of image rules, used by every path that draws an image.

    "every module contains item images, i am not able to understand which
     module is which"

Secondary images and A+ modules were generated by two different routes that
shared nothing. Everything learned by generating real images -- no medical
wording, no figure that is not in the spec, no invented ingredient, no
unprovable performance claim, and above all the product presence -- lived on the
secondary path only.

So an A+ module could print a claim a secondary image would have been stopped
from printing, and EVERY A+ module got the product photograph attached, which is
exactly what the complaint describes. That is one concept implemented twice,
which CLAUDE.md Rule 12 forbids, and this test is what stops it happening again.
"""
import ast
import io
import os
import sys

FAIL = []


def check(label, ok):
    print("  %-62s %s" % (label, "OK" if ok else "FAIL"))
    if not ok:
        FAIL.append(label)


def src(p):
    return io.open(os.path.join(os.path.dirname(os.path.abspath(__file__)), p),
                   encoding="utf-8").read()


def code_only(text):
    """Comments explain the fault; they must never be what satisfies the test.
    This is a mistake already made twice on this codebase -- an assertion
    matched a phrase that only ever appeared in the comment written to explain
    it, so the test passed while the behaviour was absent."""
    out = []
    for line in text.splitlines():
        s = line.lstrip()
        if s.startswith("#"):
            continue
        out.append(line.split("  #")[0] if "  #" in line else line)
    return "\n".join(out)


print("== the rules live in one module ==")
RULES = src("domain/image_rules.py")
check("there is a shared image-rules module", len(RULES) > 2000)
for name in ("_LIST_RULES", "_IMAGE_TEXT_RULES", "_PRESENCE_RULES",
             "_SQUARE_CANVAS", "_presence_rule"):
    check("  it owns %s" % name,
          (name + " = ") in RULES or ("def " + name) in RULES)

GEN = code_only(src("routes/genimage_routes.py"))
check("the secondary path no longer defines its own copy",
      "_IMAGE_TEXT_RULES = (" not in GEN and "_PRESENCE_RULES = {" not in GEN)
check("  it imports them instead", "from domain.image_rules import" in GEN)

APL = code_only(src("routes/aplus_routes.py"))
check("the A+ path imports the same ones",
      "from domain.image_rules import" in APL)

print("\n== an A+ module is held to what an image may say ==")
# It was not. This route built its own brief and appended nothing.
check("the text rules reach the A+ prompt", "_IMAGE_TEXT_RULES" in APL)
check("  and the drafted copy may not claim performance either",
      "how the product performs" in APL and "no 'lights fast'" in APL)

print("\n== an A+ module may be product-free ==")
check("the route accepts a presence", 'b.get("product_presence"' in APL)
check("  validated against the shared set", "_PRESENCE_RULES" in APL)
check("  defaulting to hero, so old callers are unchanged",
      'or "hero"' in APL)
check("  and the rule is put in the brief", "_PRESENCE_RULES[presence]" in APL)

# THE ACTUAL FIX. Every "do not draw the product" instruction was already
# written on the secondary path and the product appeared anyway, until the
# reference photograph stopped being attached. Handing a model a picture of a
# bottle and telling it not to draw a bottle does not work; the picture wins.
check("the photograph is WITHHELD when no product is wanted",
      "want_ref = presence != \"none\"" in APL)
check("  from the reference", "reference_image=_ref" in APL)
check("  and from the extra reference too", "extra_reference=_ref" in APL)
check("  the reference is empty when the module wants no product",
      '_ref = product_image if want_ref else ""' in APL)
# And it must not be handed a spec telling it to reproduce the product either.
check("  no 'reproduce the product precisely' spec for a product-free module",
      "if want_ref:" in APL)
check("  but it still gets the listing's own facts",
      "listing_facts" in APL)

print("\n== the moved rules still say everything they said ==")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import domain.image_rules as R  # noqa: E402

check("four presence answers", sorted(R._PRESENCE_RULES) ==
      ["detail", "hero", "in_use", "none"])
check("  'none' forbids the product anywhere in the frame",
      "THERE IS NO BOTTLE, BOX, PACK, TUB OR UNIT ANYWHERE IN THE FRAME"
      in R._PRESENCE_RULES["none"])
check("  and forbids the packaging-mockup escape route",
      "NOT the design wrapped onto a box" in R._PRESENCE_RULES["none"])
check("the text rules still ban medical wording",
      "NO health, medical, therapeutic" in R._IMAGE_TEXT_RULES)
check("  unprovable performance claims",
      "how the product PERFORMS" in R._IMAGE_TEXT_RULES)
check("  figures not in the spec", "NO number, measurement" in R._IMAGE_TEXT_RULES)
check("  invented ingredients", "NO ingredient, component or part name"
      in R._IMAGE_TEXT_RULES)
check("  and still carry the list rules",
      "NEVER pad a column" in R._IMAGE_TEXT_RULES)
check("a secondary image is still told it is square",
      "SQUARE" in R._presence_rule("hero"))

print("\n== a colour code is removed, not merely forbidden ==")
# "#B5813A" was typeset under a chef-hat mark. The rule banning it went in. Then
# "@0D0D00" was typeset in the corner of an A+ module WITH THAT RULE ALREADY IN
# THE PROMPT. That is the expected result of asking a model not to draw a token
# that is sitting in its own instructions looking like a label.
#
# So the token is taken out and replaced with the colour in words, which leaves
# nothing to typeset. An instruction can be disobeyed; a word that is not there
# cannot be drawn.
check("hex maps to a plain colour name", R.colour_name("#B5813A") == "warm brown")
check("  the A+ leak maps too", R.colour_name("@0D0D00") == "near-black")
check("  three-digit shorthand works", R.colour_name("#FFF") == "white")
check("  and nonsense returns nothing", R.colour_name("#zzz") == "")
got = R.words_for_colours("Palette: #0D0D00 with #3EDBAF accents.")
check("codes are replaced in a prompt", "#0D0D00" not in got and "#3EDBAF" not in got)
check("  by the colour in words", "near-black" in got and "mint green" in got)
# Stripping every six-hex-digit run would eat model numbers and part codes,
# which would be a worse bug than the one being fixed. The marker is required.
check("a bare number is left alone",
      R.words_for_colours("Model 123456 and part A0B1C2") ==
      "Model 123456 and part A0B1C2")
check("  and text with no codes is untouched",
      R.words_for_colours("no codes here") == "no codes here")

# It is applied at the ONE point every image path goes through, so no path can
# be added later that misses it.
AIP = code_only(src("domain/ai_providers.py"))
check("applied where every path passes", "words_for_colours(prompt)" in AIP)

print("\n== two more things that are instructions, not copy ==")
# MEASURED on one A+ module: "2010x50" set as a headline (the prompt ends
# "output the image at exactly 600x450 pixels", which reads like a line to
# typeset), and an "EST. OUTDOORS" oval stamp asserting nothing.
check("the output size may not be drawn",
      "The OUTPUT SIZE is not part of the design" in R._IMAGE_TEXT_RULES)
check("  nor the aspect ratio or resolution",
      "the aspect ratio, a resolution" in R._IMAGE_TEXT_RULES)
check("a decorative stamp counts as an invented badge",
      "EMPTY-LOOKING decorative stamp" in R._IMAGE_TEXT_RULES)
check("  named so it cannot be read past", "'EST.' oval" in R._IMAGE_TEXT_RULES)

print("\n%d failed" % len(FAIL))
for f in FAIL:
    print("  -", f)
sys.exit(1 if FAIL else 0)
