"""An image this app hosts is publishable, from the draft as well as the library.

"app should be able to upload the images without the drive as we are using it on
 server now"

Amazon does not keep the picture, it keeps the ADDRESS and re-fetches it. So a
"/media/..." path is no use to it -- but the app serves the same file at a signed
public address, and the image library has always known how to build one.

The SUBMIT path did not. build_api_attributes checked "does this start with
http" and skipped anything else, so an image generated by this app and set on a
draft was dropped on the way out and the listing published without it. Two code
paths, two answers, and the quiet one was the one that mattered (Rule 12).

The refusal is kept where it is honest: with no public base URL configured there
is no correct address, and a guessed one is WORSE than no image -- Amazon accepts
it, fetches nothing, and the listing goes up bare.
"""
import json, os, sys, tempfile

sys.path.insert(0, r"D:\AltaScraper")

fails = []
def check(l, g, w):
    ok = g == w
    if not ok: fails.append(l)
    print("  %-66s %s" % (l, "OK" if ok else "FAIL got=%r want=%r" % (g, w)))
def truthy(l, g): check(l, bool(g), True)

from domain import image_urls as I

TMP = tempfile.mkdtemp(prefix="altaimg_")
CFG = os.path.join(TMP, "config.json")
json.dump({"accounts": []}, open(CFG, "w"))
os.environ.pop("PUBLIC_BASE_URL", None)

print("=== with nowhere to serve from, it refuses rather than guesses ===")
check("no base configured", I.base_url(CFG), "")
check("  so no url is built", I.public_url(CFG, "/media/a/b.jpg"), "")
# The dangerous alternative: a link to localhost, or to whatever host happened to
# be handy, which Amazon accepts and then cannot fetch.
truthy("  and the reason is written down",
       "worse than no image" in open(r"D:\AltaScraper\domain\image_urls.py",
                                     encoding="utf-8").read())

print("\n=== configured, it builds the same address the library serves ===")
json.dump({"accounts": [], "public_base_url": "https://app.example.com"},
          open(CFG, "w"))
u = I.public_url(CFG, "/media/_acct/ws/sku/pic.jpg")
truthy("a url is built", u.startswith("https://app.example.com/img/"))
truthy("  carrying a token", "/img/" in u and len(u.split("/img/")[1].split("/")[0]) == 24)
truthy("  and the path", u.endswith("/_acct/ws/sku/pic.jpg"))
check("  the token is the one the route will re-sign",
      u.split("/img/")[1].split("/")[0], I.token(CFG, "_acct/ws/sku/pic.jpg"))

print("\n=== http is forced to https, which Amazon requires ===")
json.dump({"accounts": [], "public_base_url": "http://app.example.com"},
          open(CFG, "w"))
truthy("built as https", I.public_url(CFG, "/media/a.jpg").startswith("https://"))

print("\n=== an address that is already public is left alone ===")
check("passed through unchanged",
      I.public_url(CFG, "https://i.ebayimg.com/images/g/x/s-l1600.jpg"),
      "https://i.ebayimg.com/images/g/x/s-l1600.jpg")
check("something that is neither is refused", I.public_url(CFG, "not a url"), "")
check("  and so is a traversal", I.public_url(CFG, "/media/../../etc/passwd"), "")

print("\n=== the environment still wins, for a deployment that sets it ===")
os.environ["PUBLIC_BASE_URL"] = "https://from-env.example.com"
check("env beats config", I.base_url(CFG), "https://from-env.example.com")
os.environ.pop("PUBLIC_BASE_URL", None)

print("\n=== and the submit path uses it ===")
gen = open(r"D:\AltaScraper\amazon_listing_generator.py", encoding="utf-8").read()
truthy("build_api_attributes resolves a media path", "_fetchable(" in gen)
truthy("  through the shared builder", "_iu.public_url(CONFIG_PATH, u)" in gen)
truthy("  for the main image", '_main_img = _fetchable(' in gen)
truthy("  and every gallery slot", '_iv = _fetchable(' in gen)
truthy("  and says what to set when it cannot",
       "set \n" not in gen and "public_base_url in config.json" in gen)
# dashboard had its own copy of this; it must not drift from the one above.
dash = open(r"D:\AltaScraper\dashboard.py", encoding="utf-8").read()
truthy("the dashboard delegates rather than rebuilding it",
       "_iu.public_url(CONFIG_PATH, media_url)" in dash)

import shutil
shutil.rmtree(TMP, ignore_errors=True)
print("\nFAILURES: %d" % len(fails))
for f in fails:
    print("   -", f)
sys.exit(1 if fails else 0)
